### ISSUE TITLE
0.4.7-windows版本，运行起来后，资源文件报404

### ISSUE THREAD

**Issue by yangeren** [hidu/pproxy#11]
如题：0.4.7-windows版本，运行起来后，资源文件报404
截图：[http://prntscr.com/c1xdw4](http://prntscr.com/c1xdw4)

**Comment by hidu** [comment]
用源码按照最新dev版本吧 之前的是有问题。

**Comment by yangeren** [comment]
请问如何才能编译出exe的文件？我按照你文档里的方法：go get -u github.com/hidu/pproxy，安装完成后，bin里面的pproxy.exe，pproxy -conf=./conf/pproxy.conf 运行后报错。
