### ISSUE TITLE
怎么重定向部分URL?

### ISSUE THREAD

**Issue by ablegao** [hidu/pproxy#5]
怎么重定向部分URL? 比如，http://www.baidu.com/api/aaaaa 重定向到 http://127.0.0.1:8000/api/aaaaa ， 同时这里面还有一切其他接口：
http://www.baidu.com/api/bbbbb || cccccc 这些不被重定向

**Comment by ablegao** [comment]
还有一些重定向规则， 比如：
http://www.baidu.com/api/aaaaa
重定向到:
http://127.0.0.1:8000/aaaaaa 
url结构不相同

**Comment by hidu** [comment]
进行管理页面，修改 req rewrite 中的js代码，用js代码来实现。
点开  req demo:show/hide 可以看到示例：
比如：
```
//demo 2 
if(req.host=="www.hao123.com"){
   req.url="http://zhida.baidu.com/"
}
```


或者:
```
if(xxx){
  req.path="/"+target+req.path.substr(4);
}
```

**Comment by ablegao** [comment]
已经解决， 谢谢
