### ISSUE TITLE
panic: Here be dragons: cmpl.parseStatement(*ast.FunctionStatement)

### ISSUE THREAD

**Issue by yourchanges** [hidu/pproxy#8]
Env:
centos 6.5 x86_64 bit

golang 1.6.3

run with default configure files

[root@localhost pproxy]# ./pproxy 
panic: Here be dragons: cmpl.parseStatement(*ast.FunctionStatement)

goroutine 1 [running]:
panic(0x9df2a0, 0xc820487e90)
    /home/lee/go/src/runtime/panic.go:481 +0x3e6
github.com/hidu/pproxy/vendor/github.com/robertkrimen/otto.(__compiler).parseStatement(0xc820487e70, 0x7f4806b1ef80, 0xc8200241b0, 0x0, 0x0)
    /home/lee/gowork/src/github.com/hidu/pproxy/vendor/github.com/robertkrimen/otto/cmpl_parse.go:356 +0x983
github.com/hidu/pproxy/vendor/github.com/robertkrimen/otto.(__compiler)._parse(0xc820487e70, 0xc8204809c0, 0xc820487e70)
    /home/lee/gowork/src/github.com/hidu/pproxy/vendor/github.com/robertkrimen/otto/cmpl_parse.go:372 +0x1b3
github.com/hidu/pproxy/vendor/github.com/robertkrimen/otto.(__compiler).parse(0xc820487e70, 0xc820487e70)
    /home/lee/gowork/src/github.com/hidu/pproxy/vendor/github.com/robertkrimen/otto/cmpl.go:23 +0x49
github.com/hidu/pproxy/vendor/github.com/robertkrimen/otto.cmpl_parse(0xc8204809c0, 0x91a5c0)
    /home/lee/gowork/src/github.com/hidu/pproxy/vendor/github.com/robertkrimen/otto/cmpl_parse.go:363 +0x70
github.com/hidu/pproxy/vendor/github.com/robertkrimen/otto.(__runtime).cmpl_runOrEval(0xc820071340, 0x91a5c0, 0xc82044ef70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/lee/gowork/src/github.com/hidu/pproxy/vendor/github.com/robertkrimen/otto/runtime.go:478 +0xfa
github.com/hidu/pproxy/vendor/github.com/robertkrimen/otto.(__runtime).cmpl_run(0xc820071340, 0x91a5c0, 0xc82044ef70, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/lee/gowork/src/github.com/hidu/pproxy/vendor/github.com/robertkrimen/otto/runtime.go:493 +0x61
github.com/hidu/pproxy/vendor/github.com/robertkrimen/otto.Otto.Run(0x0, 0xc820071340, 0x91a5c0, 0xc82044ef70, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/lee/gowork/src/github.com/hidu/pproxy/vendor/github.com/robertkrimen/otto/otto.go:292 +0x5c
github.com/hidu/pproxy/serve.(_requestModifier).parseJs(0xc820135d40, 0xc8201338c0, 0x201, 0xabc020, 0x0, 0x0, 0x0, 0x0)
    /home/lee/gowork/src/github.com/hidu/pproxy/serve/req_modifer.go:96 +0x31d
github.com/hidu/pproxy/serve.(_requestModifier).tryLoadJs(0xc820135d40, 0xabc020, 0x0, 0x0, 0x0)
    /home/lee/gowork/src/github.com/hidu/pproxy/serve/req_modifer.go:47 +0xda
github.com/hidu/pproxy/serve.(_requestModifier).loadAllJs(0xc820135d40, 0x0, 0x0)
    /home/lee/gowork/src/github.com/hidu/pproxy/serve/req_modifer.go:63 +0x21f
github.com/hidu/pproxy/serve.NewProxyServe(0xb1f4b0, 0x12, 0x0, 0x7f4806b1b9d0, 0x0, 0x0)
    /home/lee/gowork/src/github.com/hidu/pproxy/serve/serve.go:168 +0x6a8
main.main()
    /home/lee/gowork/src/github.com/hidu/pproxy/proxy_main.go:42 +0x30a

**Comment by hidu** [comment]
fixd in the dev branch
